// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXYDdkQatCClaKjIQPEQrX6fjqvegoIv4',
    appId: '1:16322602925:web:ee3fe02ea8054306926324',
    messagingSenderId: '16322602925',
    projectId: 'quickhire1-688bf',
    authDomain: 'quickhire1-688bf.firebaseapp.com',
    storageBucket: 'quickhire1-688bf.firebasestorage.app',
    measurementId: 'G-LG5YNSFCKV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFxFnln6IpO1tLWSxQ95nFfv6CsFdbIJo',
    appId: '1:16322602925:android:30b5fa108b2948bf926324',
    messagingSenderId: '16322602925',
    projectId: 'quickhire1-688bf',
    storageBucket: 'quickhire1-688bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJoiwmo3HU2Mhhj7Np2pIlGvVL8_alkDI',
    appId: '1:16322602925:ios:a6dd77d43387c0d7926324',
    messagingSenderId: '16322602925',
    projectId: 'quickhire1-688bf',
    storageBucket: 'quickhire1-688bf.firebasestorage.app',
    iosClientId: '16322602925-db7c80jputkjf0m6s2pjpkhlduiv712h.apps.googleusercontent.com',
    iosBundleId: 'com.example.quickhire1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJoiwmo3HU2Mhhj7Np2pIlGvVL8_alkDI',
    appId: '1:16322602925:ios:a6dd77d43387c0d7926324',
    messagingSenderId: '16322602925',
    projectId: 'quickhire1-688bf',
    storageBucket: 'quickhire1-688bf.firebasestorage.app',
    iosClientId: '16322602925-db7c80jputkjf0m6s2pjpkhlduiv712h.apps.googleusercontent.com',
    iosBundleId: 'com.example.quickhire1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXYDdkQatCClaKjIQPEQrX6fjqvegoIv4',
    appId: '1:16322602925:web:a61d6de3fc7f9e83926324',
    messagingSenderId: '16322602925',
    projectId: 'quickhire1-688bf',
    authDomain: 'quickhire1-688bf.firebaseapp.com',
    storageBucket: 'quickhire1-688bf.firebasestorage.app',
    measurementId: 'G-QK2KNRV18E',
  );

}